### ISSUE TITLE
token doesn't update

### ISSUE THREAD

**Issue by Seiterle** [pfadiflamberg/billy#52]
In the following attempt to send emails the token is not updated. This might be an issue of Flask-Dance, if it occurs again we should check if something is miss-configured or if we can recover from this by getting a new session

```
billy-backend | 2021-08-04 21:48:17.618 | INFO     | __main__:handle_exception_error:126 - (token_expired)
billy-backend | Traceback (most recent call last):
billy-backend |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
billy-backend |     rv = self.dispatch_request()
billy-backend |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
billy-backend |     return self.view_functions[rule.endpoint](**req.view_args)
billy-backend |   File "/usr/src/app/./billy/app.py", line 295, in sendBulkInvoice
billy-backend |     for success, result in bi.get_messages(force=force):
billy-backend |   File "/usr/src/app/billy/model.py", line 92, in get_messages
billy-backend |     self.prepare()
billy-backend |   File "/usr/src/app/billy/model.py", line 113, in prepare
billy-backend |     self.user = hitobito.getUser()
billy-backend |   File "/usr/src/app/billy/hitobito.py", line 129, in getUser
billy-backend |     response = session.get('oauth/profile', headers={'X-Scope': 'with_roles'})
billy-backend |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 543, in get
billy-backend |     return self.request('GET', url, **kwargs)
billy-backend |   File "/usr/local/lib/python3.9/site-packages/flask_dance/consumer/requests.py", line 192, in request
billy-backend |     return super().request(
billy-backend |   File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 477, in request
billy-backend |     url, headers, data = self._client.add_token(
billy-backend |   File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
billy-backend |     raise TokenExpiredError()
billy-backend | oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)
billy-backend | 2021-08-04 21:48:17.628 | INFO     | __main__:handle_exception_error:131 - None
```

**Comment by Seiterle** [comment]
We could try to catch this error and send an unauthorised response, if this does not resolve the issue, we can decrease the session time of the flask dance session.
